const fs = require('fs');
const path = require('path');
const { parseCsv, JS_IDENTIFIER_RE } = require('./pack-script-includes');

// Regenerates src/data/scopes.json from a sys_scope list CSV export. See README
// ("Bundled scope list") for the export query.
//
//   node scripts/pack-scopes.js "path/to/sys_scope.csv"
//
// The Script Include whitelist only knows scopes that own at least one active
// Script Include, so `other_scope.Name` on a scope outside that set reported the
// namespace as undefined. This list makes the prefix of a `<scope>.<Name>`
// reference checkable on its own.

const OUT_PATH = path.join(__dirname, '..', 'src', 'data', 'scopes.json');
const REQUIRED_COLUMNS = ['scope'];

function main() {
  const csvPath = process.argv[2];
  if (!csvPath) {
    throw new Error('Usage: node scripts/pack-scopes.js <sys_scope.csv>');
  }
  if (!fs.existsSync(csvPath)) {
    throw new Error(`CSV not found: ${csvPath}`);
  }

  const records = parseCsv(fs.readFileSync(csvPath, 'utf8'));
  if (records.length === 0) {
    throw new Error(`No data rows parsed from ${csvPath}`);
  }
  for (const column of REQUIRED_COLUMNS) {
    if (!(column in records[0])) {
      throw new Error(
        `CSV is missing the '${column}' column. Export at least name and scope.`
      );
    }
  }

  const scopes = new Set();
  const skipped = { empty: 0, notIdentifier: 0 };
  for (const record of records) {
    const scope = record.scope;
    if (!scope) {
      skipped.empty++;
      continue;
    }
    if (!JS_IDENTIFIER_RE.test(scope)) {
      // Scope values such as `global.something` or display text can never be a
      // bare namespace identifier in a script.
      skipped.notIdentifier++;
      continue;
    }
    scopes.add(scope);
  }

  const payload = {
    version: 1,
    format: 'servicenow_scope_list',
    note:
      'Generated by scripts/pack-scopes.js from a sys_scope list export. Technical ' +
      'scope names usable as the namespace identifier in <scope>.<Name>. The ' +
      "linter drops 'global' and the caller's own scope, which follow their own " +
      'resolution rules.',
    sourceColumns: Object.keys(records[0]),
    scopes: [...scopes].sort()
  };

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, JSON.stringify(payload, null, 2) + '\n', 'utf8');

  console.log(`wrote ${OUT_PATH}`);
  console.log(`  scopes: ${payload.scopes.length}`);
  console.log(
    `  skipped: ${skipped.empty} without a scope value, ` +
      `${skipped.notIdentifier} non-identifier scopes`
  );
}

if (require.main === module) {
  main();
}
